MACRO (USE_OPENSSL)

    IF (WITH_OPENSSL)
        FIND_PACKAGE (OpenSSL REQUIRED)
        MESSAGE ("Found OpenSSL version: ${OPENSSL_VERSION} at ${OPENSSL_INCLUDE_DIR}")
        ADD_COMPILE_DEFINITIONS (WITH_OPENSSL=1)
    ENDIF ()

ENDMACRO ()
