name: Linux-ssl
# Almost the same as regular Linux builds, BUT with enabled SSL support, requires OpenSSL installed

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    uses: Enmk/clickhouse-cpp/.github/workflows/linux.yml@master
    with:
      extra_cmake_flags: -DWITH_OPENSSL=ON
      extra_install: libssl-dev
#      gtest_args: --gtest_filter="-*LocalhostTLS*"
